
import localFont from "next/font/local";
import { AppStateProvider } from "./contexts/AppStateContext";
import "./globals.css";
import AppLogo from "./components/AppLogo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {





  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased page-container`}
      >
        <AppStateProvider>
          <header>
                 <AppLogo/>
          </header>
          {children}
          <footer className="w-full h-auto bg-black text-center text-white absolute left-0 bottom-0 py-3">
             <p>Designed & developed by&nbsp;
              <a className="hover:btn-link" href="https://www.linkedin.com/in/gulshan-aggarwal-64b4121a3" target="_blank">Gulshan Aggarwal</a>
             </p>
          </footer>
        </AppStateProvider>
      </body>
    </html>
  );
}
